url: https://BlockRepublic.github.io/site
baseurl: /agency-jekyll-theme/

# Site settings
title: Block Republic
email: tom@blockrepublic.io
description: "Block Republic"


# Team names, titles and social links
people:
- name: Ay Eye
  pic: 1
  position: CEO

# Postal address (add as many lines as necessary)
address:
  - line: Wyoming

# Build settings
markdown: kramdown
permalink: pretty
